name: Destroy gaawwh

on:
  workflow_dispatch:

permissions:
  id-token: write # allow workflow to request an OIDC token from GitHub's IdP
  contents: read # grant workflow read on the repo's content

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./terraform

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::566027688242:role/GitHubOIDCRole
          aws-region: us-east-1

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3

      
      - name: Terraform fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Validate
        run: terraform validate -no-color

      - name: Terraform Plan
        run: terraform plan
        continue-on-error: true
      
      - name: Terraform Destroy upon Terraform Apply's Failure
        run: terraform destroy --auto-approve
      
      - name: Empty tfstate_bucket
        run: aws s3 rm s3://static-web-031025-terraform-state-bucket --recursive
      
      - name: Delete tfstate_bucket
        run: aws s3 rb s3://static-web-031025-terraform-state-bucket --force